### ISSUE TITLE
Error rendering AdminMetadata tab for Attachments

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1669]

**Comment by coblej** [comment]
Same error occurs on AdminMetadata tab for Targets

**Comment by coblej** [comment]
09:55:44 FATAL: 
ActionView::Template::Error (undefined method `multires_image_file_path' for #<Target:0x007fc2687e8b00>):
    2:   <% admin_metadata_fields.each do |field| %>
    3:   <tr>
    4:     <th scope="row"><%= t("dul_hydra.admin_metadata.#{field}", default: field.to_s.titleize) %></th>    
    5:     <td><%= render_admin_metadata_field field %></td>
    6:   <tr>
    7:   <% end %>
    8: </table>
  app/helpers/application_helper.rb:6:in `rescue in render_admin_metadata_field'
  app/helpers/application_helper.rb:4:in `render_admin_metadata_field'
  app/views/application/_admin_metadata_fields.html.erb:5:in `block in _app_views_application__admin_metadata_fields_html_erb___1204262617299494975_70236487145060'
  app/views/application/_admin_metadata_fields.html.erb:2:in `each'
  app/views/application/_admin_metadata_fields.html.erb:2:in `_app_views_application__admin_metadata_fields_html_erb___1204262617299494975_70236487145060'
  app/views/application/_admin_metadata.html.erb:2:in `_app_views_application__admin_metadata_html_erb__1418122477546098232_70236487094640'
  app/helpers/application_helper.rb:98:in `block in render_tab_content'
  app/helpers/application_helper.rb:97:in `render_tab_content'
  app/helpers/application_helper.rb:104:in `block in render_tabs_content'
  app/helpers/application_helper.rb:104:in `each'
  app/helpers/application_helper.rb:104:in `inject'
  app/helpers/application_helper.rb:104:in `render_tabs_content'
  app/views/application/show.html.erb:10:in `_app_views_application_show_html_erb__1585323310754067189_86408800'

**Comment by coblej** [comment]
Addressed in https://github.com/duke-libraries/dul-hydra/pull/1670 .
