### ISSUE TITLE
Title search is broken

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1693]
Selecting "Title" from search drop down results in message "Sorry, I don't understand your search."

**Comment by dchandekstark** [comment]
```
9:24:22 ERROR: RSolr::Error::Http - 500 Internal Server Error
Error: {'responseHeader'=>{'status'=>500,'QTime'=>2,'params'=>{'facet.query'=>['workflow_state_ssi:published','-workflow_state_ssi:published','is_locked_ssi:true','-is_locked_ssi:true'],'q'=>'{!qf=$title_qf pf=$title_pf}duke','facet.field'=>['active_fedora_model_ssi','admin_set_facet_sim'],'spellcheck.q'=>'duke','qt'=>'search','spellcheck.dictionary'=>'title','fq'=>'','sort'=>'title_ssi asc','rows'=>'10','wt'=>'ruby','facet'=>'true'}},'error'=>{'trace'=>'java.lang.RuntimeException
	at org.apache.solr.search.ExtendedDismaxQParser$ExtendedDismaxConfiguration.<init>(ExtendedDismaxQParser.java:1497)
	at org.apache.solr.search.ExtendedDismaxQParser.createConfiguration(ExtendedDismaxQParser.java:270)
	at org.apache.solr.search.ExtendedDismaxQParser.<init>(ExtendedDismaxQParser.java:132)
	at org.apache.solr.search.ExtendedDismaxQParserPlugin.createParser(ExtendedDismaxQParserPlugin.java:37)
	at org.apache.solr.search.QParser.getParser(QParser.java:315)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:146)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:197)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:1976)
	at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:777)

URI: https://repostore-pre.lib.duke.edu:8443/solr/production/select?wt=ruby
Request Headers: {"Content-Type"=>"application/x-www-form-urlencoded; charset=UTF-8"}
Request Data: "qt=search&facet.field=active_fedora_model_ssi&facet.field=admin_set_facet_sim&facet.query=workflow_state_ssi%3Apublished&facet.query=-workflow_state_ssi%3Apublished&facet.query=is_locked_ssi%3Atrue&facet.query=-is_locked_ssi%3Atrue&&fq=&&rows=10&spellcheck.dictionary=title&q=%7B%21qf%3D%24title_qf+pf%3D%24title_pf%7Dduke&spellcheck.q=duke&facet=true&sort=title_ssi+asc"

Backtrace: /home/hydra/.rvm/gems/ruby-2.1.5@dul-hydra/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response'
/home/hydra/.rvm/gems/ruby-2.1.5@dul-hydra/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute'
/home/hydra/.rvm/gems/ruby-2.1.5@dul-hydra/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive'
/home/hydra/.rvm/gems/ruby-2.1.5@dul-hydra/gems/blacklight-5.16.0/app/models/blacklight/solr/repository.rb:44:in `block in send_and_receive'
/home/hydra/.rvm/gems/ruby-2.1.5@dul-hydra/gems/activesupport-4.1.14/lib/active_support/benchmarkable.rb:41:in `block in benchmark'
/home/hydra/.rvm/gems/ruby-2.1.5@dul-hydra/gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/hydra/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/hydra/.rvm/gems/ruby-2.1.5@dul-hydra/gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/home/hydra/.rvm/gems/ruby-2.1.5@dul-hydra/gems/activesupport-4.1.14/lib/active_support/benchmarkable.rb:41:in `benchmark'
/home/hydra/.rvm/gems/ruby-2.1.5@dul-hydra/gems/blacklight-5.16.0/app/models/blacklight/solr/repository.rb:42:in `send_and_receive'
/home/hydra/.rvm/gems/ruby-2.1.5@dul-hydra/gems/blacklight-5.16.0/app/models/blacklight/solr/repository.rb:28:in `search' 
```
