### ISSUE TITLE
Process simple ingest throws exception trying to read config file

### ISSUE THREAD

**Issue by coblej** [duke-libraries/dul-hydra#1708]
rake aborted!
TypeError: no implicit conversion of nil into String
/srv/perkins/hydra/dul-hydra/lib/dul_hydra/scripts/process_simple_ingest.rb:43:in `read'
/srv/perkins/hydra/dul-hydra/lib/dul_hydra/scripts/process_simple_ingest.rb:43:in `load_configuration'
/srv/perkins/hydra/dul-hydra/lib/dul_hydra/scripts/process_simple_ingest.rb:15:in `initialize'
/srv/perkins/hydra/dul-hydra/lib/tasks/dul_hydra.rake:60:in `new'
/srv/perkins/hydra/dul-hydra/lib/tasks/dul_hydra.rake:60:in `block (3 levels) in <top (required)>'
/home/hydra/.rvm/gems/ruby-2.1.5@dul-hydra/bin/ruby_executable_hooks:15:in `eval'
/home/hydra/.rvm/gems/ruby-2.1.5@dul-hydra/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => dul_hydra:batch:simple_ingest
(See full trace by running task with --trace)

**Comment by coblej** [comment]
@jt112 FYI

**Comment by coblej** [comment]
@jt112 Source of problem found.  Hotfix pr being examined by Travis now.  Should have new version of staff app soon.

**Comment by coblej** [comment]
Fixed in https://github.com/duke-libraries/dul-hydra/pull/1709
